# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DeltaPluginDialog
                                 A QGIS plugin
 This plugin automates various typical tasks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-10
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Vladimir Ermolenko
        email                : ermolenko.vm@dclouds.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Delta_plugin_dialog_base.ui'))

import_ui_file, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Heat_map.ui'))


class DeltaPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DeltaPluginDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)


class HeatMap(QtWidgets.QDialog, import_ui_file):
    def __init__(self, parent=None):
        """Constructor."""
        super(HeatMap, self).__init__(parent)
        self.setupUi(self)
